GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "nynny's blog",
    "author": "nynny",
    "url": "nynnypage.com",
    "likes": 100
}
